-- Migration: add partner fields and access scopes table
-- Run this on your database (adjust types for your RDBMS)

ALTER TABLE partners
  ADD COLUMN company_code VARCHAR(64) UNIQUE,
  ADD COLUMN nomor_pks VARCHAR(64) UNIQUE,
  ADD COLUMN pic_name VARCHAR(255),
  ADD COLUMN pic_email VARCHAR(255),
  ADD COLUMN pic_phone VARCHAR(64),
  ADD COLUMN status VARCHAR(32) DEFAULT 'active';

-- A separate table for access scopes per partner
CREATE TABLE partner_access_scopes (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  partner_id BIGINT NOT NULL,
  scope_name VARCHAR(128) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT fk_partner FOREIGN KEY (partner_id) REFERENCES partners(id) ON DELETE CASCADE
);

-- Indexes
CREATE UNIQUE INDEX ux_partners_company_code ON partners(company_code);
CREATE UNIQUE INDEX ux_partners_nomor_pks ON partners(nomor_pks);
