import { NextResponse } from "next/server";

// Generate company code and PKS number client-side
// Note: In production, these should be generated by the backend to ensure uniqueness
export async function GET(request) {
  try {
    const { searchParams } = new URL(request.url);
    const name = searchParams.get("name") || "";
    const wantPks = !!searchParams.get("pks");

    // derive 3 letters from company name
    const only = name.toUpperCase().replace(/[^A-Z0-9]/g, "");
    const letters = (only.slice(0, 3) || "XXX").padEnd(3, "X");

    // Generate sequence number (timestamp-based for demo)
    // In production, backend should provide sequential numbers from database
    const seqNum = (Date.now() % 1000) + 1;
    const seq = String(seqNum).padStart(3, "0");

    const company_id = `PT-${letters}-${seq}`;

    let nomor_pks = null;
    if (wantPks) {
      const year = new Date().getFullYear();
      const pksSeq = seq;
      nomor_pks = `PKS-${year}-${pksSeq}`;
    }

    return NextResponse.json({ company_id, nomor_pks });
  } catch (err) {
    return NextResponse.json({ error: "failed" }, { status: 500 });
  }
}
